# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'note_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(392, 285)
        self.list_notes = QtWidgets.QListWidget(Dialog)
        self.list_notes.setGeometry(QtCore.QRect(20, 40, 181, 241))
        self.list_notes.setObjectName("list_notes")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(210, 50, 169, 131))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.new_note = QtWidgets.QLineEdit(self.layoutWidget)
        self.new_note.setObjectName("new_note")
        self.verticalLayout.addWidget(self.new_note)
        self.addBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.addBtn.setObjectName("addBtn")
        self.verticalLayout.addWidget(self.addBtn)
        self.deleteBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.deleteBtn.setObjectName("deleteBtn")
        self.verticalLayout.addWidget(self.deleteBtn)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(20, 10, 391, 41))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.notes = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.notes.setFont(font)
        self.notes.setObjectName("notes")
        self.horizontalLayout.addWidget(self.notes)
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.addBtn.setText(_translate("Dialog", "Добавление заметки"))
        self.deleteBtn.setText(_translate("Dialog", "Удаление заметки"))
        self.notes.setText(_translate("Dialog", "Заметки"))
        self.label.setText(_translate("Dialog", "Добавление и удаление \n"
"заметок"))
